// <auto-generated />
using System;
using Deskberry.SQLite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Deskberry.SQLite.Migrations
{
    [DbContext(typeof(DeskberryContext))]
    [Migration("20180822191644_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Deskberry.SQLite.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AvatarId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Login");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("Salt");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Deskberry.SQLite.Models.Avatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Content");

                    b.HasKey("Id");

                    b.ToTable("Avatars");
                });

            modelBuilder.Entity("Deskberry.SQLite.Models.Account", b =>
                {
                    b.HasOne("Deskberry.SQLite.Models.Avatar", "Avatar")
                        .WithMany("Accounts")
                        .HasForeignKey("AvatarId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
