// <auto-generated />
using System;
using Deskberry.SQLite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Deskberry.SQLite.Migrations
{
    [DbContext(typeof(DeskberryContext))]
    partial class DeskberryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("Deskberry.SQLite.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AvatarId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Login");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("Salt");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Deskberry.SQLite.Models.Avatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Content");

                    b.HasKey("Id");

                    b.ToTable("Avatars");
                });

            modelBuilder.Entity("Deskberry.SQLite.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Title");

                    b.Property<string>("Uri");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Deskberry.SQLite.Models.Account", b =>
                {
                    b.HasOne("Deskberry.SQLite.Models.Avatar", "Avatar")
                        .WithMany("Accounts")
                        .HasForeignKey("AvatarId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Deskberry.SQLite.Models.Favorite", b =>
                {
                    b.HasOne("Deskberry.SQLite.Models.Account", "Account")
                        .WithMany("Favorites")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
